apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milestone2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/david-maat/linux-web-services
    targetRevision: main
    path: "Milestone 2/infrastructure/dm-milestone2-chart"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: milestone2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
