apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dm-milestone2-chart.fullname" . }}-presync-wait
  labels:
    {{- include "dm-milestone2-chart.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "dm-milestone2-chart.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: wait
          image: busybox:1.36
          command: ["sh", "-c", "sleep 30"]
