apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dm-milestone2-chart.fullname" . }}-pgadmin
  labels:
    {{- include "dm-milestone2-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.adminEmail | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.adminPassword | quote }}
