apiVersion: v1
kind: Service
metadata:
  name: {{ include "dm-milestone2-chart.fullname" . }}-pgadmin
  labels:
    {{- include "dm-milestone2-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  type: {{ .Values.pgadmin.service.type }}
  ports:
    - port: {{ .Values.pgadmin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dm-milestone2-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
