apiVersion: v1
kind: Service
metadata:
  name: {{ include "dm-milestone2-chart.fullname" . }}-postgres
  labels:
    {{- include "dm-milestone2-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "dm-milestone2-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres